version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - db
    container_name: flyway-migrations
    command: -url=jdbc:postgresql://db:5432/store_db -user=user -password=password migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
