server:
  port: 8088
spring:
  application:
    name: Store
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger/index.html"